/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsViewTransitionsRouteImport } from './routes/experiments/view-transitions'
import { Route as ExperimentsCssAnchorPositionRouteImport } from './routes/experiments/css-anchor-position'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsViewTransitionsRoute =
  ExperimentsViewTransitionsRouteImport.update({
    id: '/experiments/view-transitions',
    path: '/experiments/view-transitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperimentsCssAnchorPositionRoute =
  ExperimentsCssAnchorPositionRouteImport.update({
    id: '/experiments/css-anchor-position',
    path: '/experiments/css-anchor-position',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiments/css-anchor-position': typeof ExperimentsCssAnchorPositionRoute
  '/experiments/view-transitions': typeof ExperimentsViewTransitionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiments/css-anchor-position': typeof ExperimentsCssAnchorPositionRoute
  '/experiments/view-transitions': typeof ExperimentsViewTransitionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiments/css-anchor-position': typeof ExperimentsCssAnchorPositionRoute
  '/experiments/view-transitions': typeof ExperimentsViewTransitionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/experiments/css-anchor-position'
    | '/experiments/view-transitions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/experiments/css-anchor-position'
    | '/experiments/view-transitions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/experiments/css-anchor-position'
    | '/experiments/view-transitions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExperimentsCssAnchorPositionRoute: typeof ExperimentsCssAnchorPositionRoute
  ExperimentsViewTransitionsRoute: typeof ExperimentsViewTransitionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/view-transitions': {
      id: '/experiments/view-transitions'
      path: '/experiments/view-transitions'
      fullPath: '/experiments/view-transitions'
      preLoaderRoute: typeof ExperimentsViewTransitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/css-anchor-position': {
      id: '/experiments/css-anchor-position'
      path: '/experiments/css-anchor-position'
      fullPath: '/experiments/css-anchor-position'
      preLoaderRoute: typeof ExperimentsCssAnchorPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExperimentsCssAnchorPositionRoute: ExperimentsCssAnchorPositionRoute,
  ExperimentsViewTransitionsRoute: ExperimentsViewTransitionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
